name: Release

on:
    push:
        branches:
            - main

permissions:
    contents: write
    pull-requests: write
    issues: write

jobs:
    bump-tag-version:
        name: Bump and Tag Version
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash

        steps:
            - name: Harden the runner (StepSecurity)
              uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.12.2
              with:
                  egress-policy: audit
                  allowed-endpoints: |
                      github.com:443
                      tech.jfheinrich.eu:443
                      api.github.com:443
                      objects.githubusercontent.com:443

            - name: Checkout code
              uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  fetch-depth: 0

            - name: Set up Python
              uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
              with:
                  python-version: "3.12"

            - name: Bump and Tag Version
              uses: jefflinse/pr-semver-bump@6b735b474f354e20438496d978e2a80953073d74 # v1.7.3
              id: bump
              with:
                  mode: bump
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  major-label: major release
                  minor-label: minor release
                  patch-label: patch release
                  noop-labels: |
                      documentation change
                      skip-release
                      dependencies
                  require-release-notes: true
                  release-notes-prefix: "<!--- START AUTOGENERATED NOTES --->"
                  release-notes-suffix: "<!--- END AUTOGENERATED NOTES --->"
                  with-v: true
                  base-branch: false
